# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.policies_api import PoliciesApi


class TestPoliciesApi(unittest.TestCase):
    """ PoliciesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.policies_api.PoliciesApi()

    def tearDown(self):
        pass

    def test_create_policy(self):
        """
        Test case for create_policy

        Create policy
        """
        pass

    def test_delete_policy(self):
        """
        Test case for delete_policy

        Delete policy
        """
        pass

    def test_get_metadata_definitions(self):
        """
        Test case for get_metadata_definitions

        List metadata definitions
        """
        pass

    def test_get_policy(self):
        """
        Test case for get_policy

        Get policy
        """
        pass

    def test_get_policy_collection(self):
        """
        Test case for get_policy_collection

        List policies
        """
        pass

    def test_patch_policy(self):
        """
        Test case for patch_policy

        Patch policy
        """
        pass

    def test_reset_policy(self):
        """
        Test case for reset_policy

        Reset policy to defaults
        """
        pass

    def test_update_policy(self):
        """
        Test case for update_policy

        Update policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
