# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.patterns_api import PatternsApi


class TestPatternsApi(unittest.TestCase):
    """ PatternsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.patterns_api.PatternsApi()

    def tearDown(self):
        pass

    def test_create_pattern(self):
        """
        Test case for create_pattern

        Create pattern
        """
        pass

    def test_delete_pattern(self):
        """
        Test case for delete_pattern

        Delete pattern
        """
        pass

    def test_get_pattern(self):
        """
        Test case for get_pattern

        Get pattern
        """
        pass

    def test_get_pattern_collection(self):
        """
        Test case for get_pattern_collection

        List patterns
        """
        pass

    def test_get_policies_by_pattern(self):
        """
        Test case for get_policies_by_pattern

        List policies that use a pattern
        """
        pass

    def test_update_pattern(self):
        """
        Test case for update_pattern

        Update pattern
        """
        pass


if __name__ == '__main__':
    unittest.main()
